### ISSUE TITLE
Release pertained models

### ISSUE THREAD

**Issue by Lizw14** [young-geng/m3ae_public#2]
Thanks for the amazing work! 

I am wondering if pertained M3AE and MAE models can be release, so that we (people who do not have resources for pretraining) can use the models for an apple-to-apple comparison and analysis. Thanks!

**Comment by mees** [comment]
Hi there,
same here. Would love to try out pretrained models. Can we expect them to be released soon?

**Comment by young-geng** [comment]
I've uploaded the pre-trained weights. You can find them [here](https://drive.google.com/drive/folders/1I4tD8wA4o0QiHSY-TsER9uq9rzbrokQf?usp=share_link).
